COMP: VS2010 fails to compile when inserting a null pointer in a std list.
* Using static_cast is required.

* The associated error was:

c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xmemory(208): error C2440: 'initializing' : cannot convert from 'int' to 'vtkMRMLNode *'
20>
20>  195>          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast

git-svn-id: http://svn.slicer.org/Slicer4/trunk@19079 3bd1e089-480b-0410-8dfb-8563597acbee