ENH: WIP: switch from QWebKit to QWebEngine
This code fails with the following error.  Issue appears to be that
incomplete list of frameworks is included on compile line.
Frameworks are specified somewhere in the CTK macros (TBD).

In file included from /Users/pieper/slicer4/latest/Slicer/Libs/MRML/Widgets/qMRMLChartView.cxx:36:
In file included from /Users/pieper/slicer4/latest/Slicer/Libs/MRML/Widgets/qMRMLChartView_p.h:27:
/Users/pieper/slicer4/latest/Slicer/Libs/MRML/Widgets/qMRMLChartView.h:22:10: fatal error: 'QWebEngineView' file not found
#include <QWebEngineView>